# calibration_dir: Path to where any calibration metadata is located.
# It is also used to stored generated calibrations
calibration_dir: ~/Work/smapper/calibration/kalibr/

# rosbags_dir: A directory where it contains a ros2 folder with ros2 bags.
# These bags will be converted into ros1 bags and will be saved into a ros1 directory.
# If a ros1 bag has already been converted from a ros2 bag, it is skipped.
rosbags_dir: ~/rosbags

# smapper_dir: Path to where the smapper repo is located.
# Is mainly used to retrieve the custom Dockerfile for kalibr
smapper_dir: ~/Work/smapper/

imu_config_filename: static/imu/config.yaml
kalibr_image_tag: kalibr
april_tag_filename: april_6x6_80x80cm.yaml # Relative to calibration_dir

rosbags:
    parallel_conversions: 4

calibrators:
    camera_calibrator:
        parallel_calibrations: 4
        save_dir: "static/camera" # Relative to calibration_dir
        target_filename: april_6x6_80x80cm.yaml # Relative to calibration_dir
        camera_model: pinhole-radtan # All the cameras in the rosbag must have the same model

    imu_calibrator:
        save_dir: "static/imu" # Relative to calibration_dir
        imu_config_filename: "imu_config.yaml"

    camera_imu_calibrator:
        save_dir: "dynamic/" # Relative to calibration_dir
        reprojection_sigma: 1.0
